### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by jaimesombra** [KaOS-Community-Packages/spotify#10]
I try to install spotify and every time I get this error (sorry for my english):

==> Creando el paquete: spotify 1.1.10.546-1 (dom 25 ago 2019 18:40:45 CDT)
==> Comprobando dependencias mientras se ejecuta...
==> Instalando las dependencias que faltan...
Contraseña: 
Sorry, try again.
Contraseña: 
error: no se ha encontrado el paquete: curl-kcp
==> ERROR: «pacman» ha fallado al instalar las dependencias que faltaban.

**Comment by dagodax** [comment]
You need to install curl-kcp in from kcp in first place:
kcp -i curl-kcp
And then:
kcp -i spotify
