### ISSUE TITLE
libcurl-gnutls.so.4

### ISSUE THREAD

**Issue by supersimmo** [KaOS-Community-Packages/spotify#11]
HI Folks, 

Just followed the instructions on KCP to install spotify.  Compiled and installed all fine.  However on startup I get the following error:

/usr/share/spotify/spotify: error while loading shared libraries: libcurl-gnutls.so.4: cannot open shared object file: No such file or directory

libcurl package installed on my system.

looked around online and some other distros forums talk about so.3 being needing to be renamed to so.4.  That sounds like a recipe to break things so appreciate any help in overcoming this little boggle without nasty hacks.

Thanks!

**Comment by ShalokShalom** [comment]
Yes, this is an often occurring issue. Short: This numbers are somewhat random and without your influence. I forget the exact details, while this is super annoying and you could ask demm in the IRC, how to solve that. 

See the top right on the homepage, to find the link to the IRC.
Also, the preinstalled Quassel contains it by default.

**Comment by demmm** [comment]
>Yes, this is an often occurring issue.
That is a complete falsehood.
This is just a case where a KCP app is depending on a library build on a different setting. Just read the README for the app:
https://github.com/KaOS-Community-Packages/spotify.
Not an issue, just failing to read the instructions, closing

**Comment by ShalokShalom** [comment]
I relied on its 'libcurl is installed'
You mean it needs to be compiled from KCP?
Do we know that this is not the case?

I get this issue frequently and I even remember you talking to one guy about it and the conclusion was, that we have no much influence on it and its complicated to replicate the same number behind the dot.

**Comment by demmm** [comment]
Again, read the README

**Comment by ShalokShalom** [comment]
I did. It says build libcurl.

**Comment by supersimmo** [comment]
Hi Guys, Thanks for your replies.

To be clear, I followed the README instructions to the letter. 
**kcp -di curl-kcp
kcp -i spotify**

This compiled and installed curl-kcp and also the spotify client.

I have also followed the detail on the KaOS communty page
**https://kaos-community-packages.github.io/**

Just to be sure I did not make a mistake I have followed through again today.  Unfortunately, I am still getting the same issue:

**/usr/share/spotify/spotify: error while loading shared libraries: libcurl-gnutls.so.4: cannot open shared object file: No such file or directory**

Here are the results of my Locate command showing that libcurl is installed:
**/opt/curl/lib/libcurl-gnutls.so.4**
/opt/curl/lib/libcurl.a
/opt/curl/lib/libcurl.so
/opt/curl/lib/libcurl.so.4
/opt/curl/lib/libcurl.so.4.7.0
/opt/curl/lib/pkgconfig/libcurl.pc
/opt/curl/share/aclocal/libcurl.m4
/opt/curl/share/man/man3/libcurl-easy.3
/opt/curl/share/man/man3/libcurl-env.3
/opt/curl/share/man/man3/libcurl-errors.3
/opt/curl/share/man/man3/libcurl-multi.3
/opt/curl/share/man/man3/libcurl-security.3
/opt/curl/share/man/man3/libcurl-share.3
/opt/curl/share/man/man3/libcurl-symbols.3
/opt/curl/share/man/man3/libcurl-thread.3
/opt/curl/share/man/man3/libcurl-tutorial.3
/opt/curl/share/man/man3/libcurl-url.3
/opt/curl/share/man/man3/libcurl.3
/usr/lib/libcurl.a
/usr/lib/libcurl.so
/usr/lib/libcurl.so.4
/usr/lib/libcurl.so.4.7.0
/usr/lib/pkgconfig/libcurl.pc
/usr/share/aclocal/libcurl.m4
/usr/share/man/man3/libcurl-easy.3.gz
/usr/share/man/man3/libcurl-env.3.gz
/usr/share/man/man3/libcurl-errors.3.gz
/usr/share/man/man3/libcurl-multi.3.gz
/usr/share/man/man3/libcurl-security.3.gz
/usr/share/man/man3/libcurl-share.3.gz
/usr/share/man/man3/libcurl-symbols.3.gz
/usr/share/man/man3/libcurl-thread.3.gz
/usr/share/man/man3/libcurl-tutorial.3.gz
/usr/share/man/man3/libcurl-url.3.gz
/usr/share/man/man3/libcurl.3.gz

If this is not a packaging issue Demmm are you able to further assist?

Thanks!

**Comment by abucodonosor** [comment]
Looking at the curl-kcp package , libcurl-gnutls.so.4 is a broken symlink now.

But there seems to be also a missing /etc/ld.so.conf.d/ for that package , or there could be symlinks from /opt to /usr

**Comment by abucodonosor** [comment]
Symlink should be fixed now

**Comment by supersimmo** [comment]
Very nice Abucodonosor!  All fixed and working well.

Thanks for your help!

**Comment by abucodonosor** [comment]
@supersimmo you are welcome :)
