### ISSUE TITLE
Outdate

### ISSUE THREAD

**Issue by franlinux** [KaOS-Community-Packages/spotify#3]
-> Descargando spotify-client_1.0.23.93.gd6cfae15-30_amd64.deb…
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
==> ERROR: Hubo fallos durante la descarga de http://repository.spotify.com/pool/non-free/s/spotify-client/spotify-client_1.0.23.93.gd6cfae15-30_amd64.deb
    Cancelando…
exit status 1

Pulse cualquier tecla para continuar ...

**Comment by Israphel** [comment]
Only .24 and .25 available
