### ISSUE TITLE
Error to install Spotify

### ISSUE THREAD

**Issue by D4v2z** [KaOS-Community-Packages/spotify#6]
![screenshot_20170721_191507](https://user-images.githubusercontent.com/26611092/28474596-8f2e7ea0-6e49-11e7-940f-a7fff7b313f4.png)

what can be? thanks

**Comment by ShalokShalom** [comment]
Solved

**Comment by D4v2z** [comment]
Thanks! it worked

**Comment by ShalokShalom** [comment]
Report again, if it repeats.
