### ISSUE TITLE
Error: validation control

### ISSUE THREAD

**Issue by jomada** [KaOS-Community-Packages/spotify#8]
ERROR: One or more files did not pass the validation control!
spotify-client_1.1.5.153.gf614956d-16_amd64.deb ... HA FALLADO

**Comment by ShalokShalom** [comment]
i look into this on monday, if its unresolved by then, in a hurry now. 

you can: 

you can download the PKGBUILD via ```kcp -g spotify```

and then

do ```makepkg -g``` and copy the result into the pkgbuild, then run ```makepkg -si```

**Comment by jomada** [comment]
Thanks, update the PKGBUILD here too

**Comment by ShalokShalom** [comment]
Thanks. This works with each PKGBUILD, so long as nothing else changes, is that always all that is to do.
